In [267]:
#Import the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stat
import matplotlib.pyplot as plt
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [269]:
#Load the data
rate_data=pd.read_csv("Downloads/Recommendation System (1)/Recommendation System/anime.csv")
#Exploratory Datasets
print("Total missing Values in the train dataset:",rate_data.isna().sum())
#Handle the missing values in train dataset:
for i in rate_data.select_dtypes(include="number").columns:
    rate_data=rate_data.fillna(value=rate_data[i].mean())
print("Total missing values in the train dataset after filling:\n",rate_data.isna().sum())
#find duplicates in  dataset
print("No.of duplicate in train datasets:",end=" ")
print(rate_data.duplicated().sum()) 
print(rate_data.info())

Total missing Values in the train dataset: anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64
Total missing values in the train dataset after filling:
 anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64
No.of duplicate in train datasets: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   anime_id  12294 non-null  int64  
 1   name      12294 non-null  object 
 2   genre     12294 non-null  object 
 3   type      12294 non-null  object 
 4   episodes  12294 non-null  object 
 5   rating    12294 non-null  float64
 6   members   12294 non-null  int64  
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB
None


In [271]:

rate_data1=rate_data.drop(columns=["episodes","type","genre","members"])
print(rate_data1.head(5))
#Data cleaning
ps=PorterStemmer()
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)
    

   anime_id                              name  rating
0     32281                    Kimi no Na wa.    9.37
1      5114  Fullmetal Alchemist: Brotherhood    9.26
2     28977                          Gintama°    9.25
3      9253                       Steins;Gate    9.17
4      9969                     Gintama&#039;    9.16


In [273]:
#Model Building
cv=CountVectorizer(max_features=5000,stop_words="english")
vectors=cv.fit_transform(rate_data1["name"]).toarray()
print(vectors)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [275]:
print(vectors[0])

[0 0 0 ... 0 0 0]


In [277]:
#find cosine similarities score
similarity=cosine_similarity(vectors)
print(similarity[0])
print(similarity.shape)


[1. 0. 0. ... 0. 0. 0.]
(12294, 12294)


In [278]:
def recommend(movie):
    movie_list=rate_data1[rate_data1["name"].str.contains(movie)]
    if len(movie_list):
        movie_idx=movie_list.index[0]
        distance=similarity[movie_idx]
        movies_list=sorted(list(enumerate(distance)),reverse=True, key=lambda x:x[1])[1:10]
        print("Recommendations for {}:\n".format(movie_list.iloc[0]["name"]))
        for i in movies_list:
            print(rate_data1.iloc[i[0]]["name"])

    else:
        return "No Movies found.Please check your input"




    

In [279]:
a=input("Enter the movie name")
recommend(a)


Enter the movie name kimi


'No Movies found.Please check your input'