In [89]:
#chisquare test
import itertools
import numpy as np
import scipy.stats as stat
from scipy.stats import chi2
import matplotlib.pyplot as plt
import pandas as pd
#create dataframe
data={'Satisfaction':['Very Satisfied','Satisfied','Neutral','Unsatisfied','Very Unsatisfied','Total'],
      'Smart Thermostat':[50,80,60,30,20,120],
      'Smart Light':[70,100,90,50,50,360],
      'Total':[120,180,150,80,70,600]}
customer=pd.DataFrame(data)
print(customer)
#checking two datasets
customer_table=pd.crosstab(customer["Smart Thermostat"],customer["Smart Light"])
print(customer_table)
#observed value
observed_value=customer_table.values
print("The Observed Values are:")
print(observed_value)
#Expected Value
value=stat.chi2_contingency(customer_table)
print("The Expected Values are:")
print(value)
chi_stats,pvalue,ddof,expected=value
print("Chi Square statistics:",chi_stats)
print("P value:",pvalue)
print("Degree of freedom:",ddof)
print("Expected Value:",expected)
alpha=0.05
#calculate critical value
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print("The critical value:",critical_value)
#check accept or reject null hypothesis using critical value
print("check accept or reject null hypothesis using critical value\n")
if chi_stats>=critical_value:
     print("The chisquare stastistics value:{} is greater than or equal to critical value:{}".format(chi_stats,critical_value))
     print("So,Reject null Hypothesis,There is a relationship between two categorical variables\n")
else:
    print("The chisquare stastistics value:{} is less than critical value:{}\n".format(chi_stats,critical_value))
    print("So, Accept null Hypothesis,There is a no relationship between two categorical variables\")
#check accept or reject null hypothesis using p value 
print("check accept or reject null hypothesis using p value")
if pvalue<=alpha:
    print("The P value:{} is less than or equal to alpha value:{}".format(pvalue,alpha))
    print("So,Reject null Hypothesis,There is a relationship between two categorical variables")
else:
    print("The chisquare P value:{} is greater than or equal to alpha value:{}".format(pvalue,alpha))
    print("Accept null Hypothesis,There is a no relationship between two categorical variables")


       Satisfaction  Smart Thermostat  Smart Light  Total
0    Very Satisfied                50           70    120
1         Satisfied                80          100    180
2           Neutral                60           90    150
3       Unsatisfied                30           50     80
4  Very Unsatisfied                20           50     70
5             Total               120          360    600
Smart Light       50   70   90   100  360
Smart Thermostat                         
20                  1    0    0    0    0
30                  1    0    0    0    0
50                  0    1    0    0    0
60                  0    0    1    0    0
80                  0    0    0    1    0
120                 0    0    0    0    1
The Observed Values are:
[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
The Expected Values are:
Chi2ContingencyResult(statistic=24.000000000000007, pvalue=0.2423921616705121, dof=20, expected_freq=array([[0.33333333, 0.166666